//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "pass_key")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    pub device_id: String,
    #[sea_orm(column_type = "Blob", unique)]
    pub credential_id: Vec<u8>,
    #[sea_orm(column_type = "Blob")]
    pub public_key: Vec<u8>,
    pub sign_count: i32,
    pub authentication_count: i32,
    pub last_authenticated: DateTimeWithTimeZone,
    pub name: String,
    pub attestation: String,
    #[sea_orm(column_type = "Text")]
    pub json_data: String,
    pub time_created: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
